//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockScreenerLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class BhavCopy
    {
        public string Ticker { get; set; }
        public System.DateTime Date { get; set; }
        public double O { get; set; }
        public double H { get; set; }
        public double L { get; set; }
        public double C { get; set; }
        public double Volume { get; set; }
        public long Id { get; set; }
    }
}
