//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockScreenerLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Housebreak
    {
        public long Id { get; set; }
        public double MotherCandleHigh { get; set; }
        public double MotherCandleLow { get; set; }
        public System.DateTime MotherCandleDate { get; set; }
        public Nullable<System.DateTime> BreakoutCandleDate { get; set; }
        public Nullable<double> PercentageMoveAfterBreakOut { get; set; }
        public Nullable<System.DateTime> StopLossHitDate { get; set; }
        public int NumberOfCandles { get; set; }
        public long FK_Ticker_Id { get; set; }
    
        public virtual Ticker Ticker { get; set; }
    }
}
