//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockScreenerLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Indicator
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Indicator()
        {
            this.Indicator_1 = 0D;
            this.Indicator_2 = 0D;
            this.Indicator_3 = 0D;
            this.Indicator_4 = 0D;
            this.Indicator_5 = 0D;
            this.Indicator_6 = 0D;
            this.Indicator_7 = 0D;
            this.Indicator_8 = 0D;
            this.Indicator_9 = 0D;
            this.Indicator_10 = 0D;
        }
    
        public long Id { get; set; }
        public double Indicator_1 { get; set; }
        public double Indicator_2 { get; set; }
        public double Indicator_3 { get; set; }
        public double Indicator_4 { get; set; }
        public double Indicator_5 { get; set; }
        public Nullable<double> Indicator_6 { get; set; }
        public Nullable<double> Indicator_7 { get; set; }
        public Nullable<double> Indicator_8 { get; set; }
        public Nullable<double> Indicator_9 { get; set; }
        public Nullable<double> Indicator_10 { get; set; }
        public System.DateTime Date { get; set; }
        public long FK_Ticker_Id { get; set; }
    
        public virtual Ticker Ticker { get; set; }
    }
}
