//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockScreenerLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nifty_Realty
    {
        public long Id { get; set; }
        public string Company_Name { get; set; }
        public string Industry { get; set; }
        public string Symbol { get; set; }
        public string Series { get; set; }
        public string ISIN_Code { get; set; }
    }
}
